<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14655" started-at="2021-06-09T09:54:43Z" finished-at="2021-06-09T09:54:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14655" started-at="2021-06-09T09:54:43Z" finished-at="2021-06-09T09:54:57Z">
      <class name="WithoutPOMTestCase.NoPOMTest99GuruLogin">
        <test-method status="PASS" signature="test_Home_Page_Appear_Correct()[pri:0, instance:WithoutPOMTestCase.NoPOMTest99GuruLogin@4501b7af]" name="test_Home_Page_Appear_Correct" duration-ms="14165" started-at="2021-06-09T09:54:43Z" finished-at="2021-06-09T09:54:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Home_Page_Appear_Correct -->
        <test-method status="FAIL" signature="verify_MangerID()[pri:0, instance:WithoutPOMTestCase.NoPOMTest99GuruLogin@4501b7af]" name="verify_MangerID" duration-ms="60" started-at="2021-06-09T09:54:57Z" depends-on-methods="WithoutPOMTestCase.NoPOMTest99GuruLogin.test_Home_Page_Appear_Correct" finished-at="2021-06-09T09:54:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at WithoutPOMTestCase.NoPOMTest99GuruLogin.verify_MangerID(NoPOMTest99GuruLogin.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_MangerID -->
      </class> <!-- WithoutPOMTestCase.NoPOMTest99GuruLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
